#!/bin/bash
#SBATCH --job-name=E0_3dgs
#SBATCH --output=/home/arua/thesis/logs/E0_3dgs.%j.out
#SBATCH --error=/home/arua/thesis/logs/E0_3dgs.%j.err
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --nodelist=cn13
#SBATCH --gres=gpu:a100_40gb:1
#SBATCH --mem=100G
#SBATCH --time=24:00:00
#SBATCH --partition=acltr

set -e
set -x

module purge
module load Anaconda3/2023.07-2
module load CUDA/12.1.1
eval "$(conda shell.bash hook)"
conda activate seasplat

export TMPDIR=/home/arua/tmp
ulimit -n 65536
export CUDA_HOME=/opt/itu/easybuild/software/CUDA/12.1.1
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

# SCENE=/home/arua/thesis/data/eiffel_tower/processed/scene
SCENE=/home/arua/thesis/data/eiffel_tower/subset_100
OUTPUT=/home/arua/thesis/experiments/E0_vanilla_3dgs
mkdir -p $OUTPUT

cd /home/arua/thesis/code/seasplat_underwater

python train.py \
    -s $SCENE \
    -m $OUTPUT \
    --eval \
    --iterations 30000 \
    --seed 42

echo "E0 training done"